---
- name: Create VM on Proxmox
  hosts: localhost
  gather_facts: no
  collections:
    - community.general

  vars:
    proxmox_api_host: "10.111.2.117"
    proxmox_api_user: "root@pam"
    proxmox_api_token_id: "root@pam!ansible"
    proxmox_api_token_secret: "142f8ad5-9fb7-4e92-9a54-7d724fa9ee00"
    node: "pve01"

    vm_id: 101
    vm_name: "ansible-test-vm"
    vm_cores: 2
    vm_memory: 4096      # MB
    vm_disk_size: 20G
    vm_storage: "local-zfs"
    vm_iso_storage: "local"
    vm_iso: "iso/debian-13.2.0-amd64-netinst.iso"

  tasks:
    - name: Create VM
      proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        node: "{{ node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        memory: "{{ vm_memory }}"
        cores: "{{ vm_cores }}"
        sockets: 1
        scsihw: virtio-scsi-pci
        ostype: l26
        boot: "cdn"
        ide2: "{{ vm_iso_storage }}:{{ vm_iso }},media=cdrom"
        sata0: "{{ vm_storage }}:{{ vm_disk_size }}"
        net0: "virtio,bridge=vmbr0"
        state: present
        onboot: true
