 - name: Create the VM
      ansible.builtin.uri:
        url: "https://{{ api_host }}:8006/api2/json/nodes/{{ node }}/qemu"
        method: POST
        headers:
          Authorization: "{{ proxmox_auth_cookie }}"
        body:
          vmid: "{{ next_id_response.json.data }}"
          name: 'test'
          storage: "{{ storage }}"
          cores: 6
          cpu: 'x86-64-v2-AES'
          memory: 16384
          bios: 'ovmf'
          sata0: "{{ storage }}:0,import-from={{ storage }}:888/test.vmdk"
          efidisk0: "{{ storage }}:1" # 0 to allow import-from
        body_format: json
        status_code: 200
